# -*- coding: utf-8 -*-
"""3_Exe_juntas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10KIneQUOi7fygYfodnqGkH3EYo2-J_2h
"""

'''
# Programa que pergunta hora e printa saudando
hora = int(input('Que horas são? '))
if (hora >= 8) and (hora <= 12):
    print('Bom dia!')
elif (hora >= 13) and (hora <= 18):
    print('Boa tarde!')
elif (hora >= 18) and (hora <= 23):
    print('Boa noite!')
else:
    print('Vá dormir!')

# Programa que pergunta um numero e printa par ou impar
numero = int(input('Digite um numero: '))
if numero % 2 == 0:
  print('Seu numero é par.')
else:
  print('Seu numero é impar')

# Programa que pergunta seu nome e printa se é um nome curto, normal ou grande
nome = input('Digite seu nome: ')
if int(len(nome)) <= 4:
  print('Seu nome é curto')
elif int(len(nome)) >= 5 and int(len(nome)) <= 6:
  print('Seu nome é normal')
else:
  print('Seu nome é grande')
'''
# Programa que manda mensagem correpondente a hora, print erro ao tentar nao colocar um int
entrada = input('Digite a hora em numero inteiros: ')

try:
  hora = int(entrada)

  if hora >= 8 and hora <= 11:
    print('Bom dia!')
  elif hora >= 12 and hora <= 17:
    print('Boa tarde!')
  elif hora >= 18 and hora <= 23:
    print('Boa noite!')
  else:
    print('Boa madrugada!')

except ValueError:
  print('Digite um numero válido!')