# -*- coding: utf-8 -*-
"""Atividade_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bnJfnwqVPTf3BA7Vog2fPA_Ojc3nBf92
"""

#Atividade simples aonde aprendi o conceito de criar variavies, tambem cobre: str, int, bool, float.
nome = 'Bruno'
sobrenome = 'Castro'
idade = 28
ano_nascimento = 2026 - idade
maior_de_idade = idade >= 18
altura_metros = 1.79

print('Nome:', nome)
print('Sobrenome:', sobrenome)
print('Idade:', idade)
print('Ano de nascimento:', ano_nascimento)
print('È maior de idade?', maior_de_idade)
print('Altura em metros:', altura_metros)