# -*- coding: utf-8 -*-
"""Caixa_de_supermecado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSAc2fNE9uNvii7slo8DGJe1ZXbrqgva
"""

quantidade = int(input('Quantos produtos serao cadastrados? '))
total = 0
for produto in range(quantidade):
    preco_digitado = input('Digite o preco do produto: ')
    preco = float(preco_digitado.replace(',', '.'))
    total += preco

if total >= 100:
    total_final = total * 0.90
    print('Desconto aplicado.')
else:
    total_final = total
    print('Nenhum desconto aplicado.')
print(f'Total final: R$ {total_final:.2f}')