# -*- coding: utf-8 -*-
"""Calculo_de_notas_[inrange3]

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uUCaR9UZNN-F7ZaxK6QN08QFAMNv_2u
"""

nome = input('digite o nome do estudante: ')
notas = []
for i in range(3):
    nota = float(input('digite uma nota: '))
    notas.append(nota)

    media = sum(notas) / len(notas)
    maior_nota = max(notas)
    print(f'Estudante: {nome}')
    print(F'Média: {media:,=.2f}')
    print(f'Maior nota: {maior_nota:,=.2f}')
    if media >= 7:
        print("Situação: Aprovado")
    elif media >= 5:
        print('Situação: Recuperação')
    else:
        print('Situação: Reprovado')