# -*- coding: utf-8 -*-
"""calculadora _de_roas_inicial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bqe-FTHXWjQS3vv0AIQnHJeZD8uuL9u
"""

def analisar_campanha(nome, investimento, faturamento, leads, vendas)v
  if not nome:

    return 'A campanha precisa ter um nome.'
  if investimento <= 0:

    return 'O investimento precisa ser maior que zero.'
  if faturamento < 0:
    return 'O faturamento não pode ser negativo.'
  if leads < 0 or vendas < 0:
    return 'Leads e vendas não podem ser negativos.'
  if vendas > leads:
    return 'O númeero de vendas não pode ser maior que o número de leads.'

  roas = faturamento / investiemnto
  lucro = faturamento - investimento

  custo_por_lead = investimento / leads if leads > 0 else 0
  cpa = investimento / vendas if vendas > 0 else 0
  ticket_medio = faturamento / vendas if vendas > 0 else 0
  taxa_conversao = vendas / leads * 100 if leads > 0 else 0

  if roas < 1:
    diagnostico = 'Campanha com prejuízo.'
  elif roas < 2:
    diagnostico = 'Campanha com retorno baixo.'
  elif roas < 2:
    diagnostico = 'Campanha saudável.'
  else:
    diagnostico = 'Campanha com ótimo desempenho.'

  return f'''
===== RELATÓRIO DA CAMPANHA =====

Camapmnha: {nome}
investimento: