# -*- coding: utf-8 -*-
"""calculadora imc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ph5Xz6z5_e1HXdu9h2ZLGI9KIqp77a81
"""

nome = 'Bruno'
altura = 1.79
peso = 110
imc = peso / (altura * altura)
print('Bruno tem:', altura, 'de altura', 'pesa:', peso, 'kg', 'e seu IMC é:', round(imc))