# -*- coding: utf-8 -*-
"""Calculadora_try_except

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ao4yQh55ThH11HvOxCpfwjmEOzWRlSO7
"""

#Calculadora de meta usando conceitos de try, except e ValueError:

def calcular_meta(meta, meses):
  if meta <= 0:
    return 'A meta precisa ser maior que zero.'

  if meses <= 0:
    return 'A quantida de meses precisa ser maior que zero.'

  valor_mensal = meta / meses

  return f'Você precisa guardar R${valor_mensal:.2f} por mês.'

try:
  meta = float(input('Digite o valor da sua meta: R$'))
except ValueError:
  print('Erro: a meta precisa ser um número válido.')
else:
  try:
    meses = int(input('Digite em quantos meses deseja atingir a meta: '))
  except:
    print('Erro: os meses precisam ser um número inteiro.')
  else:
    resultado = calcular_meta(meta, meses)
    print(resultado)