# -*- coding: utf-8 -*-
"""Calculadora_com_while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLD6SLzIESH1rmFnzA9M1Kn9tyLP4ZrZ
"""

'''
nome = 'Luiz Otávio'
indice = 0
novo_nome = ''
while indice < len(nome):
      letra = nome[indice]
      novo_nome += f'*{letra}'
      indice += 1

novo_nome += '*'
print(novo_nome)
'''
#Calculadora
while True: #Criou o sistema de sair do while, .lower torna qualquer input digitado mesmo em caixa alta em caixa baixa, .startswith coloca a primeira letra 's' como uma especificação para sair
      numero_1 = input('Digite um número: ')
      numero_2 = input('Digite um número: ')
      operador = input('Digite um operador (+-/*): ')

      numeros_validos = None
      try:
        num_1_float = float(numero_1)
        num_2_float = float(numero_2)
        numeros_validos = True
      except:
        numeros_validos = None

      if numeros_validos is None:
         print('um ou ambos os números digitados não são válidos.')
         continue
      operados_permitidos = '+-/*'

      if operador not in operados_permitidos:
         print('Operador invalido')
         continue

      if len(operador) > 1:
         print('Digite apenas um operador')
         continue

      if operador == '+':
          print(f'{num_1_float}+{num_2_float}=', num_1_float + num_2_float)
      elif operador == '-':
          print(f'{num_1_float}-{num_2_float}=', num_1_float - num_2_float)
      elif operador == '/':
          print(f'{num_1_float}/{num_2_float}=', num_1_float / num_2_float)
      elif operador == '*':
          print(f'{num_1_float}*{num_2_float}=', num_1_float * num_2_float)
      else:
        print('Não deveria chegar aqui.')

      sair = input('Quer sair [s]im: ').lower().startswith('s')#Qualquer input com s gera o break nesse caso

      if sair is True:
        break