# -*- coding: utf-8 -*-
"""grafico_matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13U9UlN-LPr18a5PfxX3GaAKLmwohu2RZ
"""

import matplotlib.pyplot as plt
year = [1950, 1970, 1990, 2010]
pop = [2.519, 3.692, 5.263, 6.972]
plt.plot(year, pop)
plt.show()