# -*- coding: utf-8 -*-
"""Input_name.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMtGknxuZ5335-Szsqq-morlqAPOUyyE
"""

'''
nome = 'Luiz'
preco = 1000.95897643
variavel = '%s, o preco é R$%.2f' % (nome, preco) %s pegou a string Luiz, %f pegou o preco porém o .2 cortou ele em duas casas decimais após a vírgula.
print(variavel)

Interpolação de strings com %

'''
nome = input('Digite seu nome: ')
print(f'Seu nome é: {nome}')
idade = input('Digite sua idade: ')
print(f'Sua idade é: {idade}')

if nome:
  print(f'Seu nome invertido é {nome[::-1]}')
  print(f'Seu nome tem {len(nome)} letras')
  print(f'A primeira letra do seu nome é {nome[0]}')
  print(f'A última letra do seu nome é {nome[-1]}')


  if ' ' in nome:
    print(f'{nome} Tem espaços')
  else:
    print(f'{nome} não tem espaços')

  if int(idade) >= 18:
    print('Você é maior de idade')
  elif int(idade) < 18:
    print('Você é menor de idade')

else:
  print(f'Desculpe, você deixou campos vazios.')