# -*- coding: utf-8 -*-
"""lógica_e_comparaçao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JlY6G-Bv8uy5DIOM7MZuPnagsLHBqZYt
"""

primeiro_valor = input('Digite um valor: ')
segundo_valor = input('Digite outro valor: ')

if int(primeiro_valor) > int(segundo_valor): #Compara se o valor é maior
  print(f'{primeiro_valor} é maior do que {segundo_valor}')
elif int(primeiro_valor) < int(segundo_valor): #Compara se o valor é menor
  print(f'{primeiro_valor} é menor do que {segundo_valor}')
else: #Criei só para criar um espaço de valor igual
  print('Os números são iguais')