# -*- coding: utf-8 -*-
"""Par_ou_ímpar_%

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JaTOFWEXct7u_KPykY4GITzm3jK2Dzjx
"""

numero = int(input('Saiba se seu número é par ou ímpar: '))
if numero % 2 == 0:
  print('Seu número é par')
else:
  print('Seu número é ímpar')