# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biN6CtQyqhakqykx0xe5nK9TaOol2lCu
"""

try:
  numero = int(input('Digite um numero inteiro: '))
  if numero % 2 == 0:
    print('O numero é par')
  else:
    print('O numero é impar')
except ValueError:
  print('Isso não é um numero inteiro')