# -*- coding: utf-8 -*-
"""radar_bad_run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0QB0BuuaoiOTJ41AKJ7uuxECe5w3dp0
"""

velocidade = 61
local_carro = 90

RADAR_1 = 60 #CONSTANTE SÃO VARIAVEIS QUE NÃO VÃO MUDAR DE VALOR, POR ISSO O CAPS.
LOCAL_1 = 100
RADAR_RANGE = 1

vel_carro_pass_radar_1 = velocidade > RADAR_1
carro_multado_radar_1 = local_carro >= (LOCAL_1 - RADAR_RANGE) and local_carro <= (LOCAL_1 + RADAR_RANGE)

if vel_carro_pass_radar_1:
  print("Você está multado.")
if carro_multado_radar_1 and vel_carro_pass_radar_1:
  print('Carro multado em radar 1')