# -*- coding: utf-8 -*-
"""tabuada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UseQSo0j0h7pRVARYms7VCGl-YwLdWkL
"""

'''
#Aprendendo sobre while
senha = ''

while senha != '1234':
    senha = input('Digite a senha: ')

print("Acesso liberado!")

#while continua o comando ao digitar sair você cai no break que para de executar o programa:
while True:
    nome = input('Digite seu nome ou sair: ')

    if nome == 'sair':
        break
    print(f'Olá, {nome}')
'''
numero = 1

while numero <= 7:
    multiplicador = 1
    while multiplicador <= 10:
          resultado = multiplicador * multiplicador
          print(f'{numero} X {multiplicador} = {resultado}')
          multiplicador += 1

    print('--------')
    numero += 1