# -*- coding: utf-8 -*-
"""try_except.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ao4yQh55ThH11HvOxCpfwjmEOzWRlSO7
"""

'''
#Código funcional usando conceitos aprendidos em aula passada:
print('-' * 1000)

nome = input('Digite seu nome: ')
idade = int(input('Digite sua idade: '))
salario = float(input('Digite seu salario: '))
def analisar_usuario(nome, idade, salario):

  if not isinstance(nome, str):
    return 'O nome deve ser uma string'
  if not nome:
    return 'Onome não pode estar vazio'
  if len(nome) < 3:
    return 'O nome deve ter pelo menos 3 letras'
  if  not isinstance(idade, int):
    return 'A idade deve ser um número inteiro'
  if idade < 0:
    return 'A idade não pode ser negativa'
  if idade < 18:
    status = 'menor de idade'
  else:                                 #Código que usa a mesma estrutura dos anteriores
    status = 'maior de idade'
  if not isinstance(salario, (int, float)):
    return 'O salario deve ser um numérico'
  if salario < 0:
    return 'O salario não pode ser negativo'

  nome_invertido = nome[::-1]
  primeira_letra = nome[0]
  ultima_letra = nome[-1]
  quantidade_letras = len(nome)
  idade_dividida = idade / 100
  salario_anual = salario * 12


  return (
      f'Nome: {nome}\n'
      f'Nome invertido: {nome_invertido}\n'
      f'Primeira letra: {primeira_letra}\n'
      f'Ultima letra: {ultima_letra}\n'
      f'Quantidade de letras: {quantidade_letras}\n'
      f'Idade divida por 100: {idade_dividida}\n'
      f'Salario com 10% de aumento: {salario_anual:.2f}\n'
      f'Status: {status}'
  )

print(analisar_usuario(nome, idade, salario))


print('-' * 1000)


#Conhecendo conceitos de try, except(ValueError), else:

try: #primeira tentiva:
  idade = int(input('Digite sua idade: '))
except ValueError: #Se o usuario digitar errado, no caso um número via texto, erro:
  print('Idade inválida.')
else: #Rodará por ultimo mostrando a idade do usuario:
  print(f'Sua idade é {idade}')


'''

nome = input('Digite seu nome: ')

try:
  idade = int(input('Digite sua idade: '))
except ValueError:
  print('Erro a idade deve ser um numero inteiro')
else:
  try:
    salario = float(input('Digite seu salario: '))
  except ValueError:
    print('Erro: o salário deve ser um número válido.')
  else:
    resultado = analisar_usuario(nome, idade, salario)
    print(resultado)